# Generated by Django 4.1 on 2022-10-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0004_task_is_finished_task_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="is_finished",),
        migrations.RemoveField(model_name="task", name="status",),
    ]
