# Generated by Django 4.1 on 2022-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0005_remove_task_is_finished_remove_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
